#!/usr/bin/env python3
"""
Environment Setup Helper

This script helps you configure API keys for the ByNoemie RAG Chatbot.

Usage:
    python env_setup.py              # Interactive setup
    python env_setup.py --check      # Verify current configuration
    python env_setup.py --providers  # List available providers
"""

import os
import sys
from pathlib import Path

# Project paths
PROJECT_ROOT = Path(__file__).parent
ENV_FILE = PROJECT_ROOT / ".env"
ENV_EXAMPLE = PROJECT_ROOT / ".env.example"


def check_provider(name: str, env_var: str, test_url: str = None) -> dict:
    """Check if a provider is configured and available"""
    key = os.getenv(env_var, "")
    
    result = {
        "name": name,
        "env_var": env_var,
        "configured": bool(key),
        "key_preview": f"{key[:8]}...{key[-4:]}" if len(key) > 12 else "***",
        "available": False
    }
    
    if not key:
        return result
    
    # Test availability
    try:
        if name == "Groq":
            from groq import Groq
            client = Groq(api_key=key)
            # Quick test
            result["available"] = True
        elif name == "OpenAI":
            from openai import OpenAI
            client = OpenAI(api_key=key)
            result["available"] = True
        elif name == "Anthropic":
            from anthropic import Anthropic
            client = Anthropic(api_key=key)
            result["available"] = True
        elif name == "Ollama":
            import requests
            resp = requests.get(f"{key}/api/tags", timeout=2)
            result["available"] = resp.status_code == 200
        elif name == "LangSmith":
            result["available"] = True  # Can't easily test
    except Exception as e:
        result["error"] = str(e)
    
    return result


def check_all_providers():
    """Check all configured providers"""
    # Load .env first
    if ENV_FILE.exists():
        try:
            from dotenv import load_dotenv
            load_dotenv(ENV_FILE)
        except ImportError:
            pass
    
    providers = [
        ("Groq", "GROQ_API_KEY"),
        ("OpenAI", "OPENAI_API_KEY"),
        ("Anthropic", "ANTHROPIC_API_KEY"),
        ("Ollama", "OLLAMA_BASE_URL"),
        ("LangSmith", "LANGCHAIN_API_KEY"),
    ]
    
    print("\n" + "=" * 60)
    print("🔑 API Key Configuration Status")
    print("=" * 60)
    
    any_configured = False
    
    for name, env_var in providers:
        result = check_provider(name, env_var)
        
        if result["configured"]:
            any_configured = True
            status = "✅" if result.get("available") else "⚠️ "
            print(f"\n{status} {name}")
            print(f"   Key: {result['key_preview']}")
            if result.get("error"):
                print(f"   Error: {result['error']}")
        else:
            print(f"\n❌ {name}")
            print(f"   Not configured (set {env_var})")
    
    print("\n" + "-" * 60)
    
    if not any_configured:
        print("⚠️  No providers configured!")
        print("\nQuick setup:")
        print("  1. Get a FREE Groq API key: https://console.groq.com")
        print("  2. Run: python env_setup.py")
    else:
        print("✅ At least one provider is configured")
    
    print()


def interactive_setup():
    """Interactive environment setup"""
    print("\n" + "=" * 60)
    print("🚀 ByNoemie RAG Chatbot - Environment Setup")
    print("=" * 60)
    
    # Check if .env exists
    if ENV_FILE.exists():
        print(f"\n⚠️  .env file already exists at {ENV_FILE}")
        overwrite = input("Overwrite? (y/N): ").strip().lower()
        if overwrite != 'y':
            print("Setup cancelled. Run --check to verify current config.")
            return
    
    env_content = []
    env_content.append("# ByNoemie RAG Chatbot - Environment Configuration")
    env_content.append("# Generated by env_setup.py\n")
    
    # Groq (recommended)
    print("\n" + "-" * 40)
    print("1. GROQ (FREE - Recommended)")
    print("   Get key at: https://console.groq.com")
    print("-" * 40)
    groq_key = input("Enter GROQ_API_KEY (or press Enter to skip): ").strip()
    if groq_key:
        env_content.append(f"GROQ_API_KEY={groq_key}")
    
    # OpenAI
    print("\n" + "-" * 40)
    print("2. OPENAI (Paid)")
    print("   Get key at: https://platform.openai.com/api-keys")
    print("-" * 40)
    openai_key = input("Enter OPENAI_API_KEY (or press Enter to skip): ").strip()
    if openai_key:
        env_content.append(f"OPENAI_API_KEY={openai_key}")
    
    # Anthropic
    print("\n" + "-" * 40)
    print("3. ANTHROPIC (Paid)")
    print("   Get key at: https://console.anthropic.com")
    print("-" * 40)
    anthropic_key = input("Enter ANTHROPIC_API_KEY (or press Enter to skip): ").strip()
    if anthropic_key:
        env_content.append(f"ANTHROPIC_API_KEY={anthropic_key}")
    
    # LangSmith
    print("\n" + "-" * 40)
    print("4. LANGSMITH (Optional - for tracing)")
    print("   Get key at: https://smith.langchain.com")
    print("-" * 40)
    langsmith_key = input("Enter LANGCHAIN_API_KEY (or press Enter to skip): ").strip()
    if langsmith_key:
        env_content.append(f"\n# LangSmith Tracing")
        env_content.append(f"LANGCHAIN_API_KEY={langsmith_key}")
        env_content.append("LANGCHAIN_TRACING_V2=true")
        env_content.append("LANGCHAIN_PROJECT=bynoemie-rag-chatbot")
    
    # Write .env file
    if len(env_content) > 2:  # More than just headers
        with open(ENV_FILE, 'w') as f:
            f.write('\n'.join(env_content) + '\n')
        
        print(f"\n✅ Created {ENV_FILE}")
        print("\n🔒 Security reminders:")
        print("   - Never commit .env to git (already in .gitignore)")
        print("   - Keep your API keys secret")
        print("   - Use different keys for dev/production")
        
        # Verify
        print("\n" + "=" * 60)
        check_all_providers()
    else:
        print("\n⚠️  No keys provided. Setup cancelled.")


def show_providers():
    """Show available providers with links"""
    print("\n" + "=" * 60)
    print("🔌 Available LLM Providers")
    print("=" * 60)
    
    providers = [
        {
            "name": "Groq",
            "cost": "FREE ⭐",
            "models": "Llama 3.1 70B, Mixtral",
            "speed": "Very Fast",
            "url": "https://console.groq.com",
            "env_var": "GROQ_API_KEY"
        },
        {
            "name": "OpenAI",
            "cost": "Paid ($0.15-$10/1M tokens)",
            "models": "GPT-4o, GPT-4o-mini",
            "speed": "Fast",
            "url": "https://platform.openai.com/api-keys",
            "env_var": "OPENAI_API_KEY"
        },
        {
            "name": "Anthropic",
            "cost": "Paid ($0.25-$15/1M tokens)",
            "models": "Claude 3 Haiku/Sonnet/Opus",
            "speed": "Fast",
            "url": "https://console.anthropic.com",
            "env_var": "ANTHROPIC_API_KEY"
        },
        {
            "name": "Ollama",
            "cost": "FREE (Local)",
            "models": "Llama, Mistral, etc.",
            "speed": "Depends on hardware",
            "url": "https://ollama.com",
            "env_var": "OLLAMA_BASE_URL"
        },
    ]
    
    for p in providers:
        print(f"\n📦 {p['name']} - {p['cost']}")
        print(f"   Models: {p['models']}")
        print(f"   Speed: {p['speed']}")
        print(f"   Get key: {p['url']}")
        print(f"   Env var: {p['env_var']}")
    
    print("\n" + "-" * 60)
    print("💡 Recommendation: Start with Groq (FREE) for development")
    print()


def main():
    """Main entry point"""
    if len(sys.argv) > 1:
        arg = sys.argv[1].lower()
        
        if arg in ('--check', '-c'):
            check_all_providers()
        elif arg in ('--providers', '-p'):
            show_providers()
        elif arg in ('--help', '-h'):
            print(__doc__)
        else:
            print(f"Unknown option: {arg}")
            print("Use --help for usage")
    else:
        interactive_setup()


if __name__ == "__main__":
    main()
